SHELL := /bin/bash
IPMT = ../bin/ipmt
PATTERN_FILE = ../tests/testfiles/patterns.txt
help:
	@echo "Atenção: os arquivos de teste devem ser adicionados previamente.";
	@echo "Para executar os testes, use "make Ti", onde i é o número do teste.";
	@echo "Além das dependências de execução do comando (GCC), para executar os testes também é necessário python."
	@echo "Os resultados de cada teste ficarão na pasta ./results";